== What You Will Build

You will create a batch program which will load sise data from text files into MySQL database.

== What You Need

* https://dev.mysql.com/downloads/[MySQL] version 5.6 or better.

NOTE: https://hevodata.com/learn/installing-mysql-on-ubuntu-20-04/[Installing MySQL on Ubuntu 20.04: 6 Easy Steps]

* https://ubasti.tistory.com/4[MySql Korean character setting]

----
sudo vi /etc/mysql/my.conf
----
----
[client]
default-character-set = utf8
[mysqld]
character-set-client-handshake=FALSE
init_connect="SET collation_connection = utf8_general_ci"
init_connect="SET NAMES utf8"
character-set-server = utf8
collation-server = utf8_general_ci
[mysqldump]
default-character-set = utf8
[mysql]
default-character-set = utf8
----
----
sudo service mysql restart
----
----
mysql> show variables like 'c%';
----

* https://zetawiki.com/wiki/MySQL_%EC%9B%90%EA%B2%A9_%EC%A0%91%EC%86%8D_%ED%97%88%EC%9A%A9[MySQL 원격 접속 허용]

* java_version: 1.8

NOTE: https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-22-04[How To Install Java with Apt on Ubuntu 22.04]

* https://melonicedlatte.com/2021/07/11/174700.html[스프링(Spring), 스프링 부트(Spring Boot)란? 개념 정리]

== Create the Database

See the following guide. 

https://github.com/spring-guides/gs-accessing-data-mysql

For the HelloWorld program reference, see the following guide.

https://github.com/spring-guides/gs-maven

== Build Java code

To try out the build, issue the following at the command line:

----
mvn compile
----

This will run Maven, telling it to execute the _compile_ goal. When it's finished, you should find the compiled _.class_ files in the _target/classes_ directory.

----
mvn clean package
----

This will make a spring-boot fat jar file.

* https://stackoverflow.com/questions/38792031/springboot-making-jar-files-no-auto-configuration-classes-found-in-meta-inf[making spring-boot fat jar pom.xml addition]

----
mvn spring-boot:run -Dspring-boot.run.arguments="WORK_FLAG INPUT_FILENAME MAX_CNT"
mvn spring-boot:run -Dspring-boot.run.arguments="olpr /root/data/TB_COE221M_OLPR_OTHER.txt 10"
mvn spring-boot:run -Dspring-boot.run.arguments="olpr /root/data/TB_COE221M_OLPR_OTHER.txt 0"
java -jar gs-maven-0.1.0.jar olpr /root/data/TB_COE221M_OLPR_OTHER.txt 10
----

----
java -jar gs-maven-0.1.0.jar addr /root/data/TB_COA115M_STNMGRP.txt 0
java -jar gs-maven-0.1.0.jar map /root/data/TB_COE101R_SISEMAP.txt 0
java -jar gs-maven-0.1.0.jar kbSise /root/data/TB_COE202D_KBPTYSISE.txt 0
java -jar gs-maven-0.1.0.jar kabSise /root/data/TB_COE211D_KABPTYSISE.txt 0

java -jar gs-maven-0.1.0.jar olpr /root/data/TB_COE221M_OLPR_BS.txt 0
java -jar gs-maven-0.1.0.jar olpr /root/data/TB_COE221M_OLPR_SU.txt 0
java -jar gs-maven-0.1.0.jar olpr /root/data/TB_COE221M_OLPR_GG.txt 0
java -jar gs-maven-0.1.0.jar olpr /root/data/TB_COE221M_OLPR_IC.txt 0

java -jar gs-maven-0.1.0.jar ehpr /root/data/TB_COE222M_EHPR.txt 0
java -jar gs-maven-0.1.0.jar olpr /root/data/TB_COE221M_OLPR_OTHER.txt 0
----

This will run the batch program. The batch program will automatically create DB tables if there aren't any.

== Create indexes on the DB tables
* CREATE INDEX ix_addr ON tb_addr (city_cd, sggu_cd, emd_cd);
* CREATE INDEX ix_map ON tb_map (stnm_unon_cd, sise_dvcd);
* CREATE INDEX ix_kb_sise ON tb_kb_sise (kb_hs_dstg_no, kb_pty_seq);
* CREATE INDEX ix_kab_sise ON tb_kab_sise (kab_dnji_no, kab_pty_no);
* CREATE INDEX ix_olpr ON tb_olpr (twprc_dnji_no, twprc_dong_no, twprc_ho_no);
* CREATE INDEX ix_ehpr ON tb_ehpr (lwdg_cd, ltno_bno, ltno_buno);


